---
title: "Untitled"
author: "Nathan Lyell"
date: "2023-10-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
fib = c(0,1)
for (i in 3:10){
  fib[i] = fib[i-1]+fib[i-2]
}
fib
```


```{r}
fib <- function(n=20){
  my_list = c(0,1)
  for (i in 3:n){
  my_list[i] = my_list[i-1]+my_list[i-2]
  return(my_list)
  }
  
}
print(fib(20))
```

```{r}
between <- function(x){
  return(x>= 0 & x<= 1)
}
between(.04)

```


```{r}
between(1)
between(0.5)
between(-0.5)
between(20005)
between(-5.5)
```

```{r}
first_10 <- letters[1:10]
first_10
last_10 <- tail(LETTERS,10)
last_10
between_let <- LETTERS[22:24]
between_let
```


```{r}
for (i in 1:100){
  print(i)
  if(i%%3 == 0 & i%%5 == 0){
    print("FizzBuzz")
  }
  else if(i%%3 == 0){
    print("Fizz")
  }
  else if(i%%5 == 0){
    print("Buzz")
  }
}
```

```{r}
txt <- "hello, This is my world now. This is not that great"
cured <- unlist(strsplit(tolower(txt),' '))
new_txt <- unique(cured)
new_txt
```

